export 'event_modal.dart';
export 'notice_modal.dart';
export 'assignment_modal.dart';
export 'attendance_modal.dart';
export 'alumni_modal.dart';
export 'faculty_modal.dart';
export 'subject_modal.dart';
export 'student_modal.dart';
export 'class_modal.dart';
